name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'temurin'
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Run tests and generate Jacoco report
        run: ./gradlew testDebugUnitTest jacocoTestReportDebug
      - name: SonarCloud Scan
                - name: Build and analyze
                env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                run: ./gradlew test jacocoTestReportRelease sonar
