name: Code Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Gradle wrapper permission
        run: chmod +x gradlew

      - name: Run tests and generate coverage report
        run: |
          ./gradlew clean test jacocoTestReport
          ls -R build/reports/jacoco/test/

      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          ls -R build/reports/jacoco/tests/
          ./gradlew jacocoTestReportRelease
