name: Coverage Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'temurin'  # Используем temurin вместо adoptopenjdk
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Run tests and generate Jacoco report
        run: ./gradlew testDebugUnitTest jacocoTestReportDebug
      - name: Upload Jacoco report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: jacoco-reports/testDebugUnitTest/
      - name: Publish to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          ./gradlew coverallsJacoco
